import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <nav>
                    <div className="navbar_items">
                        <Link href="/initial_quote">Initial Quotes</Link>
                        <Link href="/final_quote">Final Quotes</Link>
                        <Link href="/invoices">Invoices</Link>
                        <Link href="/tracking">Tracking</Link>
                    </div>
                </nav>
                {children}
            </body>
        </html>
    );
}
